---
- name: Build application and docker image
  hosts: build-host
  become: true
  vars:
    app_src_dir: /tmp/my-app
    docker_image: "led98/my-app:latest"
    dockerhub_username: "led98"
    dockerhub_password: ""

  tasks:
    - name: Update packages
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install required packages
      apt:
        pkg:
          - docker.io
          - openjdk-11-jdk
          - maven
        update_cache: yes

    - name: Clone application source
      git:
        repo: "https://github.com/AizenDev/boxfuse-sample-java-war-hello.git"
        dest: "{{ app_src_dir }}"
        version: "main"

    - name: Build application with Maven
      command: "mvn clean package -DskipTests"
      args:
        chdir: "{{ app_src_dir }}"

    - name: Login to Docker Hub
      community.docker.docker_login:
        registry_url: "https://index.docker.io/v1/"
        username: "{{ dockerhub_username }}"
        password: "{{ dockerhub_password }}"
      no_log: true

    - name: Build Docker image
      community.docker.docker_image:
        name: "{{ docker_image }}"
        source: build
        build:
          path: "{{ app_src_dir }}"
          pull: yes
        push: yes
