---
- hosts: deploy-host
  become: true
  vars:
    container_name: "java-app"
    docker_image: "led98/my-app:latest"
    dockerhub_username: "led98"
    dockerhub_password: ""
  tasks:
    - name: Update packages
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install required packages
      apt:
        pkg:
          - docker.io
          - python3-docker
          - python3-pip
          - python3-setuptools
          - openjdk-11-jdk
        update_cache: yes

    - name: Login to Docker Hub
      community.docker.docker_login:
        registry_url: "https://index.docker.io/v1/"
        username: "{{ dockerhub_username }}"
        password: "{{ dockerhub_password }}"
      no_log: false

    - name: Pull Docker image
      community.docker.docker_image:
        name: "{{ docker_image }}"
        source: pull

    - name: Stop and remove existing container
      community.docker.docker_container:
        name: "{{ container_name }}"
        state: absent
        force_kill: yes

    - name: Run application container
      community.docker.docker_container:
        name: "{{ container_name }}"
        image: "{{ docker_image }}"
        ports:
          - "8080:8080"
        restart_policy: always
        detach: yes
